spring:
  datasource:
    driverClassName: org.h2.Driver
    password: ''
    url: jdbc:h2:mem:testdb;INIT=CREATE SCHEMA IF NOT EXISTS MAIN;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    open-in-view: false
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: main
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true
  liquibase:
    change-log: ${CHANGE_LOG_PATH:classpath:db/db.changelog-master.xml}
    default-schema: main
    liquibase-schema: main
    password: ''
    url: jdbc:h2:mem:testdb;INIT=CREATE SCHEMA IF NOT EXISTS MAIN;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    user: sa
